OPTION(NO_SOUND "Turn off sound support" OFF)
MESSAGE( STATUS "Turn off sound support NO_SOUND=${NO_SOUND}" )
OPTION(INF_BUILD "" OFF)
MESSAGE( STATUS "INF_BUILD=${INF_BUILD}" )
OPTION(SCP_LITE "" OFF)
MESSAGE( STATUS "SCP_LITE=${SCP_LITE}" )
OPTION(FS2_DEMO "Build demo" OFF)
MESSAGE( STATUS "Build demo FS2_DEMO=${FS2_DEMO}" )
OPTION(SPEECH "Build speech recognition (Windows only)" ON)
IF(WIN32)
	OPTION(JPEG_STATIC "Build statically with the included jpeg library" ON)
ELSEIF(WIN32)
	OPTION(JPEG_STATIC "Build statically with the included jpeg library" OFF)
ENDIF(WIN32)
MESSAGE( STATUS "Build speech recognition (Windows only) SPEECH=${SPEECH}" )


IF(NOT WIN32)
	SET(SPEECH OFF)
ENDIF(NOT WIN32)
