IF(NOT CPACK_GENERATOR)
	SET( CPACK_GENERATOR "DEB")
ENDIF(NOT CPACK_GENERATOR)
MESSAGE( STATUS "Package CPACK_GENERATOR=${CPACK_GENERATOR}" )

SET( CPACK_PACKAGE_DESCRIPTION_SUMMARY "Freespace 2 Source Code Project" )
SET( CPACK_PACKAGE_VENDOR "Szymon Sobik" )
SET( CPACK_PACKAGE_CONTACT "Szymon Sobik kibos@poczta.fm" )
SET( CPACK_PACKAGE_VERSION_MAJOR ${CMAKE_MAJOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_MINOR ${CMAKE_MINOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_PATCH ${CMAKE_PATCH_VERSION} )
#todo will need to tie that to some variable
SET( CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386" )
SET( CPACK_PACKAGE_VERSION "${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION}-0" )
SET( CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README" )
SET( CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/COPYING" )
SET( CPACK_PACKAGE_FILE_NAME "fs2open_${CPACK_PACKAGE_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}" )
SET( CPACK_PACKAGE_NAME "fs2open" )
#todo more executables might come along
SET( CPACK_PACKAGE_EXECUTABLES "fs2open" "Freespace 2 Source Code Project" )
#todo make deps according to the build
SET( CPACK_DEBIAN_PACKAGE_DEPENDS "libvorbis0a (>=1.2), libvorbisfile3 (>=1.2), libtheora0 (>=1.0), libopenal1 (>=1.4), libgl1 (>=7.4), libsdl1.2debian (>=1.2.12)" )
#DEBIAN_PACKAGE_SECTION
INCLUDE( CPack )
